name: "Frogbot"
on:
  # After a pull request opened, Frogbot automatically creates the "🐸 frogbot scan" label if needed.
  # After "🐸 frogbot scan" label was added to a pull request, Frogbot scans the pull request.
  pull_request_target:
    types: [labeled, opened]
jobs:
  scan-pull-request:
    environment: frogbot
    runs-on: ubuntu-latest
    environment: frogbot
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: samrjfrog/jfrogbot@main
        env:
          # [Mandatory] JFrog platform URL
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD}}

          # [Mandatory if JF_USER and JF_PASSWORD are not provided] 
          # JF_ACCESS_TOKEN: ${{ secrets.FROGBOT_ACCESS_TOKEN }}
          
          # [Manadatory] The GitHub token automatically generated for the job
          # JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
